apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "laa-manage-a-providers-data.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "413,502,504"
    {{- if .Values.ingress.cluster.name }}
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $fullName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{- .Values.ingress.cluster.weight -}}"
    {{- if .Values.whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ include "laa-manage-a-providers-data.whitelist" . }}"
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine Off
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-get-access"
